// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzz70_6a0wpqu1xveOjIlAcB9aelJJ7wQ',
    appId: '1:645264070961:web:b9f147812b24d799cbb810',
    messagingSenderId: '645264070961',
    projectId: 'notes-a62d4',
    authDomain: 'notes-a62d4.firebaseapp.com',
    storageBucket: 'notes-a62d4.firebasestorage.app',
    measurementId: 'G-RPYL8D38DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCXXKwcLhV4iwliVJ9XxMMRse0HQdivU',
    appId: '1:645264070961:android:8808968c56458ce1cbb810',
    messagingSenderId: '645264070961',
    projectId: 'notes-a62d4',
    storageBucket: 'notes-a62d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrCI3X7A1xh7CloyQ4QyE72-FMhlu-yas',
    appId: '1:645264070961:ios:22506ce2220d54c4cbb810',
    messagingSenderId: '645264070961',
    projectId: 'notes-a62d4',
    storageBucket: 'notes-a62d4.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrCI3X7A1xh7CloyQ4QyE72-FMhlu-yas',
    appId: '1:645264070961:ios:22506ce2220d54c4cbb810',
    messagingSenderId: '645264070961',
    projectId: 'notes-a62d4',
    storageBucket: 'notes-a62d4.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzz70_6a0wpqu1xveOjIlAcB9aelJJ7wQ',
    appId: '1:645264070961:web:d791ec9fd2e4c54ccbb810',
    messagingSenderId: '645264070961',
    projectId: 'notes-a62d4',
    authDomain: 'notes-a62d4.firebaseapp.com',
    storageBucket: 'notes-a62d4.firebasestorage.app',
    measurementId: 'G-MRVD2LGQ8S',
  );
}
