// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATC7Qati0NLf7b3-sa9VroA2L_GGdwv64',
    appId: '1:666998007799:web:54b19d82c7a572d990f0f2',
    messagingSenderId: '666998007799',
    projectId: 'daftarbelanja-5bdc7',
    authDomain: 'daftarbelanja-5bdc7.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-5bdc7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5bdc7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqVp_etFAYVQ2Cj3bDdQv38zdQeciMZAM',
    appId: '1:666998007799:android:048293d88732c88290f0f2',
    messagingSenderId: '666998007799',
    projectId: 'daftarbelanja-5bdc7',
    databaseURL: 'https://daftarbelanja-5bdc7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5bdc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB469BeeUhqyR6ytRBd86KCFxchCj6iBq0',
    appId: '1:666998007799:ios:5d2182cf4b4d1a6790f0f2',
    messagingSenderId: '666998007799',
    projectId: 'daftarbelanja-5bdc7',
    databaseURL: 'https://daftarbelanja-5bdc7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5bdc7.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB469BeeUhqyR6ytRBd86KCFxchCj6iBq0',
    appId: '1:666998007799:ios:5d2182cf4b4d1a6790f0f2',
    messagingSenderId: '666998007799',
    projectId: 'daftarbelanja-5bdc7',
    databaseURL: 'https://daftarbelanja-5bdc7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5bdc7.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATC7Qati0NLf7b3-sa9VroA2L_GGdwv64',
    appId: '1:666998007799:web:52623920871ce98190f0f2',
    messagingSenderId: '666998007799',
    projectId: 'daftarbelanja-5bdc7',
    authDomain: 'daftarbelanja-5bdc7.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-5bdc7-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-5bdc7.firebasestorage.app',
  );
}
