// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWXu1ojvJKM4mSaEDXtUDfoUbFR1qrbW0',
    appId: '1:306942443425:web:80c24c87aee4656a8755e0',
    messagingSenderId: '306942443425',
    projectId: 'mdpgold-8a108',
    authDomain: 'mdpgold-8a108.firebaseapp.com',
    databaseURL: 'https://mdpgold-8a108-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-8a108.firebasestorage.app',
    measurementId: 'G-26NHVVLQCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILfQvgGxWZhxvrc4C9vXRC5WbArOMNYY',
    appId: '1:306942443425:android:a43b53eb07dcfd318755e0',
    messagingSenderId: '306942443425',
    projectId: 'mdpgold-8a108',
    databaseURL: 'https://mdpgold-8a108-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-8a108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZdq57hnaDG5Ymj7igL5Oo8tqyfvu7Yoc',
    appId: '1:306942443425:ios:28c3e1425323bf6e8755e0',
    messagingSenderId: '306942443425',
    projectId: 'mdpgold-8a108',
    databaseURL: 'https://mdpgold-8a108-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-8a108.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZdq57hnaDG5Ymj7igL5Oo8tqyfvu7Yoc',
    appId: '1:306942443425:ios:28c3e1425323bf6e8755e0',
    messagingSenderId: '306942443425',
    projectId: 'mdpgold-8a108',
    databaseURL: 'https://mdpgold-8a108-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-8a108.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWXu1ojvJKM4mSaEDXtUDfoUbFR1qrbW0',
    appId: '1:306942443425:web:9726e9ffebd0e4098755e0',
    messagingSenderId: '306942443425',
    projectId: 'mdpgold-8a108',
    authDomain: 'mdpgold-8a108.firebaseapp.com',
    databaseURL: 'https://mdpgold-8a108-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-8a108.firebasestorage.app',
    measurementId: 'G-QVK4EC1SWN',
  );
}
